### ISSUE TITLE
Supmua.org not working

### ISSUE THREAD

**Issue by lukeadams** [sup-heliotrope/sup-heliotrope.github.io#10]
<img width="627" alt="screen shot 2016-11-05 at 20 47 00" src="https://cloud.githubusercontent.com/assets/3508077/20034789/072e7300-a399-11e6-9aca-aa7a643a5ed5.png">

**Comment by gauteh** [comment]
Yep, it should no longer be referenced. Readme and stuff should already be updated.

**Comment by gauteh** [comment]
Right - I did not realize that supmua.org had been registered again. Should work now.
